spring:
  application:
    name: ags
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server.port: 8225
